BE_OS_Appointment functionality fixed
YuraRov/vetClinic pull request #101
Opened 2022-05-27 21:25 UTC by OliaStfn

2022-05-28 17:44 UTC, FedorivRostik approved these changes

2022-05-28 19:51 UTC, YuraRov requested changes
In AppointmentService _logger should be called after _repository.SaveChanges

2022-05-28 20:56 UTC, sefirus approved these changes

2022-05-29 09:51 UTC, YuraRov approved these changes

2022-05-29 09:52 UTC, merged