Specialization setup with repository
YuraRov/vetClinic pull request #17
Opened 2022-05-20 13:58 UTC by TRybina132

2022-05-20 14:31 UTC, YuraRov requested changes
Please name all async methods with suffix Async, for example, AddSpecializationAsync()

2022-05-21 08:00 UTC, YuraRov requested changes

2022-05-21 08:00 UTC, YuraRov commented on Core/Interfaces/Repositories/ISpecializationRepository.cs
> +        Task<ICollection<Specialization>> GetAllSpecializationsAsync();
```suggestion
        Task<IEnumerable<Specialization>> GetAllSpecializationsAsync();
```

2022-05-21 08:00 UTC, YuraRov commented on DataAccess/Repositories/SpecializationRepository.cs
> +        public Task<Specialization> AddSpecializationAsync(Specialization specialization)
```suggestion
        public async Task<Specialization> AddSpecializationAsync(Specialization specialization)
```
The same thing for other async methods

2022-05-21 08:14 UTC, YuraRov approved these changes

2022-05-21 08:28 UTC, FedorivRostik requested changes
issued extra usings

2022-05-21 08:37 UTC, FedorivRostik approved these changes

2022-05-21 08:37 UTC, YuraRov approved these changes

2022-05-21 08:39 UTC, merged