Resolved test's conflicts
YuraRov/vetClinic pull request #178
Opened 2022-07-04 19:42 UTC by FedorivRostik

Resolved test's conflicts

2022-07-04 19:44 UTC, YuraRov approved these changes

2022-07-04 20:24 UTC, YuraRov requested changes
Please correct all typo, which I described in our  Telegram group

2022-07-05 06:25 UTC, YuraRov approved these changes

2022-07-05 06:54 UTC, Strafe153 approved these changes

2022-07-05 06:55 UTC, merged