added financial statement
YuraRov/vetClinic pull request #179
Opened 2022-07-05 05:38 UTC by DarkenHouk

2022-07-05 09:50 UTC, sefirus approved these changes

2022-07-05 17:17 UTC, TRybina132 requested changes

2022-07-06 08:53 UTC, DeniesLie commented on WebApi/Controllers/FinancialController.cs
>          [HttpGet("/api/[controller]/")]
Route "/api/[controller]/" for action is redundant since the controller already has this route

2022-07-06 08:55 UTC, DeniesLie approved these changes

2022-07-06 10:10 UTC, merged