Fixed tests
YuraRov/vetClinic pull request #198
Opened 2022-07-09 22:09 UTC by OliaStfn

2022-07-09 22:59 UTC, TRybina132 approved these changes

2022-07-10 00:02 UTC, FedorivRostik approved these changes

2022-07-10 08:01 UTC, YuraRov requested changes
1. In files Application/Services/AppointmentService.cs and DataAccess/Repositories/AppointmentRepository.cs, please remove excess usings.
2. You can also delete the commented logger call in Application/Services/AppointmentService.cs.
3. In your tests, you did not "put all arrange sections" in the fixture, especially in that part of code where you test UpdateAsync method.

2022-07-10 19:57 UTC, YuraRov approved these changes

2022-07-10 20:00 UTC, merged