Adding dbContext
YuraRov/vetClinic pull request #7
Opened 2022-05-18 11:57 UTC by TRybina132

2022-05-18 12:30 UTC, FedorivRostik commented on DataAccess/Context/ClinicContext.cs
> +        public ClinicContext() { }
```suggestion

```

2022-05-18 12:30 UTC, FedorivRostik commented on DataAccess/Context/ClinicContext.cs
> +        public ClinicContext(DbContextOptions options) : base(options) { }
```suggestion
        public ClinicContext(DbContextOptions<ClinicContext> options) : base(options) { }
```

2022-05-18 12:32 UTC, FedorivRostik requested changes
Add builder.Services.AddDbContext<ClinicContext>(options=>options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

2022-05-18 17:36 UTC, FedorivRostik commented on Host/Host.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.5" />
```suggestion

```

2022-05-18 17:37 UTC, FedorivRostik commented on Host/Host.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.5" />
We don't need that

2022-05-18 18:02 UTC, YuraRov approved these changes
Everything seems to be ok :)

2022-05-18 18:02 UTC, YuraRov commented on Host/Host.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.5" />
> We don't need that

Are you sure?

2022-05-18 18:30 UTC, YuraRov requested changes
Microsoft.EntityFrameworkCore package in Host.csproj is unnecessary

2022-05-18 20:14 UTC, FedorivRostik approved these changes
Alles ist gut

2022-05-19 06:21 UTC, YuraRov approved these changes
All right

2022-05-19 06:22 UTC, merged